language: python
os:
  - linux
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.6-dev

# command to install dependencies
install: "pip install pandas Cython"
# command to run tests
script: 
  - python setup.py install
  - nosetests
  
